apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: model-input
  labels:
    strimzi.io/cluster: "strimzi-kafka"
spec:
  partitions: 2
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: model-output
  labels:
    strimzi.io/cluster: "strimzi-kafka"
spec:
  partitions: 2
  replicas: 1