apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: input
  labels:
    strimzi.io/cluster: "fashion-recognition"
spec:
  partitions: 2
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: output
  labels:
    strimzi.io/cluster: "fashion-recognition"
spec:
  partitions: 2
  replicas: 1